# Generated by Django 4.1.7 on 2023-05-08 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_tag_product_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_format',
            new_name='format',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='name',
        ),
    ]
